[package]
name = "rini-skylight-sys"
version = "0.1.0"
edition = "2024"
build = "build.rs"
description = "Raw declarations for the private SkyLight / CGS API."
license = "Apache-2.0"
publish = false

[lib]
doctest = false

[dependencies]
bitflags = { workspace = true }
num_enum = { workspace = true }
objc2-application-services = { workspace = true }
objc2-core-foundation = { workspace = true, features = ["std"] }
objc2-core-graphics = { workspace = true }
objc2-foundation = { workspace = true, features = ["std"] }
once_cell = { workspace = true, features = ["std"] }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
serde_json = { workspace = true }
